local _, addon = ...
local ADDON = addon and addon.API
local PANEL_NAME = "Nick Prefix Remover"

if not ADDON then
    return
end

local allControls = {}

local function CreateLabel(parent, text, x, y, font)
    local label = parent:CreateFontString(nil, "ARTWORK", font or "GameFontNormal")
    label:SetPoint("TOPLEFT", parent, "TOPLEFT", x, y)
    label:SetText(text)
    return label
end

local function CreateValue(parent, text, x, y, width, font)
    local value = parent:CreateFontString(nil, "ARTWORK", font or "GameFontHighlight")
    value:SetPoint("TOPLEFT", parent, "TOPLEFT", x, y)
    value:SetWidth(width)
    value:SetJustifyH("LEFT")
    value:SetText(text or "")
    return value
end

local function CreateButton(parent, text, width, height, onClick)
    local button = CreateFrame("Button", nil, parent, "UIPanelButtonTemplate")
    button:SetSize(width, height)
    button:SetText(text)
    button:SetScript("OnClick", onClick)
    return button
end

local function RefreshAll()
    local db = ADDON.GetDB()
    for _, control in ipairs(allControls) do
        control:SetChecked(db[control.settingKey] == true)
    end
end

local function MakeCheck(parent, key, label, y)
    local check = CreateFrame("CheckButton", nil, parent, "InterfaceOptionsCheckButtonTemplate")
    check.settingKey = key
    check:SetPoint("TOPLEFT", 16, y)
    check.Text:SetText(label)
    check.Text:SetFontObject(GameFontHighlight)

    check:SetScript("OnClick", function(self)
        ADDON.GetDB()[key] = self:GetChecked() == true
        ADDON.ApplyFilters()
        RefreshAll()
    end)

    allControls[#allControls + 1] = check
end

local function BuildTabbedContent(parent, tabY, pageY, contentWidth)
    contentWidth = contentWidth or 560

    local pages = {}
    local tabs = {}

    local function CreatePage()
        local page = CreateFrame("Frame", nil, parent)
        page:SetPoint("TOPLEFT", 0, pageY)
        page:SetPoint("BOTTOMRIGHT", 0, 0)
        return page
    end

    pages.options = CreatePage()
    pages.readme = CreatePage()

    local function ShowPage(name)
        for pageName, page in pairs(pages) do
            page:SetShown(pageName == name)
        end

        for tabName, tab in pairs(tabs) do
            local selected = tabName == name
            tab:SetEnabled(not selected)

            local text = tab:GetFontString()
            if text then
                if selected then
                    text:SetTextColor(1.0, 0.82, 0.0)
                else
                    text:SetTextColor(1.0, 1.0, 1.0)
                end
            end
        end
    end

    local optionsTab = CreateFrame("Button", nil, parent, "UIPanelButtonTemplate")
    optionsTab:SetText("Options")
    optionsTab:SetSize(112, 22)
    optionsTab:SetPoint("TOPLEFT", parent, "TOPLEFT", 16, tabY)
    optionsTab:SetScript("OnClick", function()
        ShowPage("options")
    end)
    tabs.options = optionsTab

    local readmeTab = CreateFrame("Button", nil, parent, "UIPanelButtonTemplate")
    readmeTab:SetText("README")
    readmeTab:SetSize(112, 22)
    readmeTab:SetPoint("LEFT", optionsTab, "RIGHT", 6, 0)
    readmeTab:SetScript("OnClick", function()
        ShowPage("readme")
    end)
    tabs.readme = readmeTab

    MakeCheck(pages.options, "enabled", "Enable nickname-prefix removal", -8)
    MakeCheck(pages.options, "fastPrefixPrecheck", "Use optimized prefix detection", -38)

    CreateLabel(pages.options, "Chat channels to filter", 16, -70)

    MakeCheck(pages.options, "guild", "Guild", -98)
    MakeCheck(pages.options, "officer", "Officer", -128)
    MakeCheck(pages.options, "party", "Party", -158)
    MakeCheck(pages.options, "raid", "Raid", -188)
    MakeCheck(pages.options, "instance", "Instance / Battleground", -218)
    MakeCheck(pages.options, "channel", "Custom channels (CHAT_MSG_CHANNEL)", -248)
    MakeCheck(pages.options, "say", "Say", -278)
    MakeCheck(pages.options, "yell", "Yell", -308)
    MakeCheck(pages.options, "whisper", "Whisper", -338)
    MakeCheck(pages.options, "bnwhisper", "Battle.net Whisper", -368)
    MakeCheck(pages.options, "communities", "Community channel", -398)

    CreateValue(
        pages.options,
        "Changes apply immediately. Open the README tab for recognised formats and limitations.",
        16,
        -434,
        contentWidth
    )

    CreateLabel(pages.readme, "How it works", 16, -8)

    local readme = CreateValue(pages.readme, nil, 16, -38, contentWidth)
    readme:SetJustifyV("TOP")
    readme:SetText([[Nick Prefix Remover hides nickname labels that other addons add at the start of incoming chat messages. It is intended for messages generated by addons such as Name2Chat and Incognito.

Recognised examples:
  (krix): Hello!
  ( krix ): Hello!
  [krix]: Hello!
  {krix}: Hello!
  <krix>: Hello!

Whitespace around a nickname and its colon is accepted, so forms such as "( krix ) : Hello!" are also removed.

Optimized prefix detection is enabled by default. It skips full pattern matching when a message does not begin (after whitespace) with (, [, {, or <. Disabling it restores the legacy matching path; recognised formats stay the same.

Important: the addon recognises a bracketed label followed by a colon at the very start of a message. This can occasionally match an ordinary player message too. For example, "(something): I agree" may be treated as a nickname prefix and become "I agree". If this is a concern, disable filtering for the affected chat channel.]])

    ShowPage("options")
end

local settingsPanel = CreateFrame("Frame", "NickPrefixRemoverOptionsPanel")
settingsPanel.name = PANEL_NAME

local settingsTitle = settingsPanel:CreateFontString(nil, "ARTWORK", "GameFontNormalLarge")
settingsTitle:SetPoint("TOPLEFT", 16, -16)
settingsTitle:SetText(PANEL_NAME)

local settingsSubtitle = settingsPanel:CreateFontString(nil, "ARTWORK", "GameFontHighlight")
settingsSubtitle:SetPoint("TOPLEFT", settingsTitle, "BOTTOMLEFT", 0, -8)
settingsSubtitle:SetText("Remove nickname prefixes from incoming chat messages.")

BuildTabbedContent(settingsPanel, -76, -106, 560)
settingsPanel:SetScript("OnShow", RefreshAll)
settingsPanel.OnRefresh = RefreshAll

local category
if Settings and Settings.RegisterCanvasLayoutCategory then
    category = Settings.RegisterCanvasLayoutCategory(settingsPanel, PANEL_NAME)
    Settings.RegisterAddOnCategory(category)
elseif InterfaceOptions_AddCategory then
    InterfaceOptions_AddCategory(settingsPanel)
end

local dialog = CreateFrame("Frame", "NickPrefixRemoverDialog", UIParent, "BasicFrameTemplateWithInset")
dialog:SetSize(480, 565)
dialog:SetPoint("CENTER")
dialog:SetFrameStrata("DIALOG")
dialog:SetToplevel(true)
dialog:SetMovable(true)
dialog:SetClampedToScreen(true)
dialog:EnableMouse(true)
dialog:RegisterForDrag("LeftButton")
dialog:SetScript("OnDragStart", dialog.StartMoving)
dialog:SetScript("OnDragStop", dialog.StopMovingOrSizing)
dialog:SetScript("OnShow", RefreshAll)

if dialog.TitleText then
    dialog.TitleText:SetText(PANEL_NAME)
end

local dialogContent = dialog.Inset or dialog
BuildTabbedContent(dialogContent, -38, -68, 410)

local footer = CreateFrame("Frame", nil, dialog)
footer:SetPoint("BOTTOMLEFT", dialog, "BOTTOMLEFT", 10, 8)
footer:SetPoint("BOTTOMRIGHT", dialog, "BOTTOMRIGHT", -10, 8)
footer:SetHeight(30)

local footerLine = footer:CreateTexture(nil, "ARTWORK")
footerLine:SetPoint("TOPLEFT", 0, 0)
footerLine:SetPoint("TOPRIGHT", 0, 0)
footerLine:SetHeight(1)
footerLine:SetColorTexture(0.55, 0.45, 0.20, 0.75)

local closeButton = CreateButton(footer, CLOSE, 110, 22, function()
    dialog:Hide()
end)
closeButton:SetPoint("BOTTOMRIGHT", -4, 0)

dialog:Hide()

function ADDON.OpenOptions()
    dialog:Show()
    dialog:Raise()
end